### ISSUE TITLE
TypeError: element.type.toLowerCase is not a function

### ISSUE THREAD

**Issue by valerion1** [react-icons/react-icons#204]
Hi guys!
i have some problem using react-icons. My project: react 16.5 + next.js 6.1, i installed package `npm install react-icons --save`
after i try to use:
```jsx
import { FaBeer } from 'react-icons/fa';
...
<FaBeer/>
```

and now while i load page i get this error:

```
element.type.toLowerCase is not a function

TypeError: element.type.toLowerCase is not a function
    at ReactDOMServerRenderer.renderDOM (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2304:28)

    at ReactDOMServerRenderer.render (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2298:21)

    at ReactDOMServerRenderer.read (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)

    at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)

    at renderPage (/app/node_modules/next/dist/server/render.js:275:26)

    at Function.getInitialProps (/app/node_modules/next/dist/server/document.js:67:25)

    at _callee$ (/app/node_modules/next/dist/lib/utils.js:111:30)

    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)

    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)

    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)

    at step (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)

    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)

    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)

    at new F (/app/node_modules/core-js/library/modules/_export.js:35:28)

    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
```

What is causing this error?

**Comment by foladipo** [comment]
Although I'm using v2 of this package, I am also experiencing this same problem. Attempts to use the package's icons fail with an error equivalent to the above. And when I eliminate using all of them, the app works fine.

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (node_modules/react-dom/cjs/react-dom-server.node.development.js:2304:28)
    at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:2298:21)
    at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at Promise.all.then.data (src/server/index.tsx:84:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Perhaps a pointer to the root cause of the bug is the fact that both of us experiencing this problem have server-side rendering set up?

**Comment by foladipo** [comment]
**UPDATE**: I found a solution that works for me on v2 of this package. Instead of importing the icons like this:

`import FaSearch from "react-icons/lib/fa/search"`

I import them like this for files where the error above occurs:

`import * as FaSearch from "react-icons/lib/fa/search"`

**Comment by kamijin-fanta** [comment]
@valerion1 if you still cannot resolve this error, please provide repository.

**Comment by valerion1** [comment]
@kamijin-fanta @foladipo thanks for answers! 

error resolved itself after updating most of the main packages (it seems the problem was in their interaction). I can assume that because of the update to [next.js](https://www.npmjs.com/package/next) to version 7.
