### ISSUE TITLE
error while in pollyfill running a jest test in p

### ISSUE THREAD

**Issue by daniloab** [react-icons/react-icons#409]
While running a jest test after installing the react-icons, started to give  the following error:

```terminal
 export * from './fa';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      4 | import { Flex, Text } from 'rebass';
      5 | import { useTranslation } from 'react-i18next';
    > 6 | import {
        | ^
      7 |   MdTrendingUp,
      8 |   MdPersonAdd,
      9 |   MdInsertChart,
```

So, following the issue https://github.com/testing-library/react-testing-library/issues/707 from RTL and https://github.com/react-icons/react-icons/issues/286

I added the following line to my `jest.config.file `:

```js
transformIgnorePatterns: [
    'node_modules/(?!react-icons|)',
  ],
```

and added `allowJs: true` to my tsconfig.json

but, even with both my test still broken giving now the following error:

```terminal
    TypeError: (0 , _typeof2.default) is not a function

      1 | import 'raf/polyfill';
      2 | 
    > 3 | if (typeof Promise === 'undefined') {
        | ^
      4 |   // Rejection tracking prevents a common issue where React gets into an
      5 |   // inconsistent state due to an error, but it gets swallowed by a Promise,
      6 |   // and the user has no idea what causes React's erratic future behavior.

      at Object.<anonymous> (../../node_modules/core-js/internals/global.js:13:82)
      at Object.<anonymous> (../../node_modules/core-js/internals/path.js:3:14)
      at Object.<anonymous> (../../node_modules/core-js/internals/define-well-known-symbol.js:3:12)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.symbol.iterator.js:3:29)
      at Object.<anonymous> (../../node_modules/@babel/runtime/helpers/typeof.js:7:1)
      at Object.<anonymous> (../../node_modules/core-js/internals/export.js:5:39)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.array.slice.js:5:9)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.symbol.description.js:9:1)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.symbol.js:7:1)
      at Object.<anonymous> (../../node_modules/core-js/internals/well-known-symbol.js:3:1)
      at Object.<anonymous> (../../node_modules/core-js/internals/to-string-tag-support.js:3:23)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.object.to-string.js:3:29)
      at Object.<anonymous> (../../node_modules/core-js/modules/es.date.to-string.js:5:1)
      at Object.<anonymous> (config/polyfill.js:3:1)
``` 

What can I do to fix this?

 - PC
 - Mojave
 - Chrome

**Comment by daniloab** [comment]
Fixed here importing from specific folder of type from icon, like `react-icons/md` instead of import from `react-icons/all`

**Comment by daniloab** [comment]
reopening to understand how to make works when importing from `/all`

**Comment by joshuamorris23** [comment]
```

```
