### ISSUE TITLE
Not building with webpack NODE_ENV=production

### ISSUE THREAD

**Issue by alex-wilmer** [react-icons/react-icons#50]
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-icons' in '/Users/awilmer/Projects/legacy-portal-relay'
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/awilmer/Projects/legacy-portal-relay/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/webpack/lib/NormalModuleFactory.js:94:20
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:726:13
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:52:16
    at done (/Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:241:17)
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:44:16
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:723:17
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/async/lib/async.js:167:37
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/webpack/lib/NormalModuleFactory.js:89:22
    at onResolved (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:68:11)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:136:10)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Tapable.applyPluginsAsyncSeriesBailResult1 (/Users/awilmer/Projects/legacy-portal-relay/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:123:19)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:136:10)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Tapable.applyPluginsAsyncSeriesBailResult1 (/Users/awilmer/Projects/legacy-portal-relay/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:123:19)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/Resolver.js:121:11)
    at loggingCallbackWrapper (/Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/awilmer/Projects/legacy-portal-relay/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:45:5
resolve 'react-icons' in '/Users/awilmer/Projects/legacy-portal-relay'
  Parsed request is a module
  using description file: /Users/awilmer/Projects/legacy-portal-relay/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/awilmer/Projects/legacy-portal-relay/package.json (relative path: .)
    resolve as module
      /Users/awilmer/Projects/node_modules doesn't exist or is not a directory
      /Users/awilmer/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/awilmer/Projects/legacy-portal-relay/node_modules
        using description file: /Users/awilmer/Projects/legacy-portal-relay/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/awilmer/Projects/legacy-portal-relay/package.json (relative path: ./node_modules)
          using description file: /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons.json doesn't exist
            as directory
              existing directory
                using path: /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/index
                  using description file: /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/index doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/awilmer/Projects/legacy-portal-relay/node_modules/react-icons/index.json doesn't exist
```

**Comment by alex-wilmer** [comment]
"react-icons": "^2.2.1",

**Comment by ammichael** [comment]
I also have this problem. Sad to know it's been opened one month ago and still no answer =(

**Comment by bentatum** [comment]
I'll look into this asap.

**Comment by bentatum** [comment]
@ammichael @alex-wilmer Is this still a problem? I can't seem to reproduce on my end.

**Comment by sandoche** [comment]
Hi ! I have the same problem, is there a way to fix it ? @ammichael @alex-wilmer

**Comment by sandoche** [comment]
Hi @bentatum I found the issue:
I had to remove "react-icons" from dependencies and add it to the devDependencies.

So for the webpack user the good solution is to do 
npm install react-icons --save-dev

**Comment by owcc** [comment]
I have the same problem ... It looks no solution so far 😞

**Comment by mmahalwy** [comment]
I get this in production:
```
index.js:13 Uncaught TypeError: Cannot read property 'string' of undefined
    at Object../node_modules/react-icon-base/lib/index.js (index.js:13)
    at Q (es6.string.from-code-point.js:4)
    at Object../node_modules/react-icons/lib/ti/plus.js (index.js:13)
    at Q (es6.string.from-code-point.js:4)
    at Object../app/containers/Tasks/index.js (index.js:66)
```

**Comment by kamijin-fanta** [comment]
Please open again if there is an update
