### ISSUE TITLE
[Bug]: FaHouse not exported, but listed on docs

### ISSUE THREAD

**Issue by lukasfarina** [react-icons/react-icons#773]
### Describe the bug

I get an error trying to import FaHouse from FontAwesome:

`sidebar.jsx:1 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_fa.js?v=60f44d8a' does not provide an export named 'FaHouse' (at sidebar.jsx:1:41)`

### Expected behavior

I was hoping to get the icon pack as it is listed in the documentation

### Minimal sample repository URL

https://react-icons.github.io/react-icons/icons?name=fa6

### Steps To Reproduce

1. npm i react-icons
2. import { FaHouse } from 'react-icons/fa';
3. Put <FaHouse /> in a component

### Package version

4.10.1

### Relevant log output

```Shell
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_fa.js?v=60f44d8a' does not provide an export named 'FaHouse' (at sidebar.jsx:1:41)
```

**Comment by lukasfarina** [comment]
That solves it! I will close the issue. Thank you @mvaibhav77
